### ISSUE TITLE
extractCategories fails on some example wikitext

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/CommonsExtension#1]
Running the `value.extractCategories()` expression on the following cell value should give some categories as output, but it returns the empty list:
```
== {{int:filedesc}} ==
{{Information
|Description={{en|1=View of Earth taken during ISS Expedition 30.}}
|Source=[https://eol.jsc.nasa.gov/SearchPhotos/photo.pl?mission=ISS030&roll=E&frame=226922 JSC Gateway to Astronaut Photography of Earth]
|Date=2012-04-12 05:20:47
|Author=Earth Science and Remote Sensing Unit, NASA Johnson Space Center
|Permission=
|other_versions=
|other_fields=
{{InFi|name=Sun Azimuth|value=33°}}
{{InFi|name=Sun Elevatation|value=-34°}}
{{InFi|name=Altitude|value={{convert|211|nmi|km}}}}
{{InFi|name=Mission|value=ISS030}}
{{InFi|name=Roll|value=E}}
{{InFi|name=Frame|value=226922}}
{{InFi|name=Camera|value=NIKON D3S S/N: 2008336}}
{{InFi|name=Focal length|value=28 mm}}
}}

{{location}}

{{NASA-image|id=ISS030-E-226922|center=JSC}}
== {{int:license-header}} ==
{{PD-USGov-NASA}}

[[Category:ISS Expedition 30 Crew Earth Observations (dump)|226922]]
[[Category:Taken with Nikon D3s]]
```

I would be curious to know why, and if it can be fixed :)

**Comment by trnstlntk** [comment]
Not sure if this is a helpful comment at all, but: in `[[Category:ISS Expedition 30 Crew Earth Observations (dump)|226922]]`, the `|226922` bit is a [sort key](https://www.mediawiki.org/wiki/Help:Categories#Sort_key). You can see that in action [in the category itself](https://commons.wikimedia.org/wiki/Category:ISS_Expedition_30_Crew_Earth_Observations_(dump)), where the images are sorted by (in this case) this frame number. I'm kinda sure that an OpenRefine user will not want that bit extracted - they will just want the `Category:ISS Expedition 30 Crew Earth Observations (dump)` or `ISS Expedition 30 Crew Earth Observations (dump)` part.

**Comment by wetneb** [comment]
@j-sal here is an example of usage of the `AstVisitor` I was mentioning:
https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/importers/WikitextImporter.java#L154
Basically you should be able to do something like this (rough code that I have not tested):
```
class CategoriesExtractor extends AstVisitor<WtNode> {

    public List<String> categories = new ArrayList<>();
     
     public void visit(WtInternalLink internalLink) {
          // here, inspect the internalLink and add it to the list of results (the 'categories' field above) if it starts with 'Category:'
     }
}

// in your grel function
CategoriesExtractor extractor = new CategoriesExtractor();
extractor.go(parsedArticle);
result = extractor.categoriers;
```
