### ISSUE TITLE
Wikidata and Wikibase reconciliation services don't load in OpenRefine 3.8.0 

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/CommonsExtension#120]
Wikidata and Wikibase reconciliation services don't load in OpenRefine 3.8.0. I have seen this on my mac (in Chrome, Firefox) and it has been reported on OpenRefine on PAWS too. On my partner's PC it did work.

Reconciliation does work with various non-Wikibase reconciliation services and with the Wikimedia Commons one. It doesn't work with Wikidata's and with a few Wikibases' I've tried (at least I think they are Wikibases - Kunstmuseum.nl and the EU knowledge graph)

The recon window doesn't appear to load anything 
![image](https://github.com/OpenRefine/OpenRefine/assets/9881645/1d947d8b-a8a8-472d-9dfd-724fb8ae8ebf)

In the terminal log, nothing happens (nothing is logged) when doing the reconciliation steps.

This is what I get in the browser console.
![image](https://github.com/OpenRefine/OpenRefine/assets/9881645/98092e93-fef0-4252-82e6-03cb1d82d1f0)

**Comment by lokal-profil** [comment]
On the Commons Extension side. This is no longer an issue with OpenRefine 3.8.2 and CommonsExtension 0.1.2 right? @trnstlntk

Is there anything left here to do on the Commons-extenison side? @wetneb

**Comment by wetneb** [comment]
Yes this was fixed by #104
