### ISSUE TITLE
Design workflows for Commons extension that don't start from a ready-made spreadsheet

### ISSUE THREAD

**Issue by lozanaross** [OpenRefine/CommonsExtension#13]
Workflows starting from a URL, or from a local folder of files, or from a Commons category tree need additional design and development. Should be discussed at a team meeting, plus a survey should go out to users - to better understand what scenarios users need more support with.

**Comment by lozanaross** [comment]
Here's a first draft of the survey: https://forms.gle/5tckun9f8nydSRjb9 

@trnstlntk have a look at it when you can & make any edits (I'll give you editing access). 

Hoping we can send it out sometime next week to all relevant user channels.

**Comment by trnstlntk** [comment]
The survey will be closed later this week. 29 responses so far! @lozanaross is producing a summary which will also be published on Wikimedia Commons.

**Comment by trnstlntk** [comment]
The survey has concluded, and @lozanaross has published the results on Wikimedia commons, see https://commons.wikimedia.org/wiki/File:Analysis_of_the_first_OpenRefine_SDC_open_survey.pdf

32 responses in total!

In general, the survey results confirm that we are on the right track with regards to editing existing sets of files (adding structured data to them). Survey participants indicate they'd like to use _"workflows we’re already working towards accommodating fully: namely starting from a well prepared spreadsheet (>65%), or starting from a Wikimedia category(ies) and ‘pulling’ associated files (>60%). Most of the other answers that got close to a third of participants’ ticks, include workflows that we also already considered, e.g. starting from an XML metadata file, or supplying a list of URLs pointing to the source files."_

When it comes to uploading new files to Wikimedia Commons: _"The most popular mental model of starting the media upload process is to start from a folder with media files on one’s own machine (>65% of participants ticked this option). However, many users also ticked the option to start by preparing a spreadsheet with all the relevant data (>50%). Many (roughly a third) also selected various options that start from an institutional repository (or other external web resource) and involve some level of data exporting or URL gathering, etc., to be then imported into OpenRefine."_

More outcomes at https://commons.wikimedia.org/wiki/File:Analysis_of_the_first_OpenRefine_SDC_open_survey.pdf

**Comment by lozanaross** [comment]
We discussed all this during the planning and strategy brainstorm on 25.04. We drafted the possible options on paper, so I need to: 

- [ ]  transfer the main steps into a Miro board for our digital record.

**Comment by lozanaross** [comment]
@trnstlntk I've added the new workflows  based on the brainstorm meetings from 25.04. in Miro: https://miro.com/app/board/uXjVOd-Sag8=/?share_link_id=546097358653

I have actually simplified some steps, so feedback is welcome as to whether the diagrammes make sense and are something we can use to communicate with other stakeholders. 

Below I've matched screenshots from the Miro board to hand-drawn diagrams from the meeting:
![Image](https://user-images.githubusercontent.com/25489750/172223573-337ad2d1-e835-4c74-9c46-d1d74d8dc900.jpg)
![Image](https://user-images.githubusercontent.com/25489750/172223598-64969192-9587-4983-a0d8-d5ff53eee421.png)

![Image](https://user-images.githubusercontent.com/25489750/172223732-085b15a2-9e6a-4d19-8047-19ea768a5741.jpg)
![Image](https://user-images.githubusercontent.com/25489750/172223733-89487eaa-589c-4ff6-adb4-a1b10001d909.jpg)

![Image](https://user-images.githubusercontent.com/25489750/172223825-378ee260-cdae-43c1-b536-9a1c46789b64.png)
![Image](https://user-images.githubusercontent.com/25489750/172223824-b133c938-0eb7-4306-8674-f9d950c61955.png)

![Image](https://user-images.githubusercontent.com/25489750/172223856-abe4e795-b474-4005-afc3-4ae3f61a80ce.jpg)
![Image](https://user-images.githubusercontent.com/25489750/172223900-dfdbca42-60aa-4e71-b383-71451d0e8ce9.png)

**Comment by trnstlntk** [comment]
@lozanaross I'm doing some cleanup of SDC-related issues - I think the workflow design itself is done, and hence this task can be closed? If you agree, feel free to do the deed :D
