### ISSUE TITLE
Finalize basic Commons-specific schema template specifications: Information, Artwork, Art Photo, Book

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/CommonsExtension#20]
We've continued thinking about Wikimedia Commons-specific template support inside OpenRefine's Wikibase schema builder.

We've come up with the concept of _'schema templates'_: basically, these are empty Wikibase schemas inside OpenRefine. For the Wikimedia Commons use case, we want to add a few default ones corresponding to frequently-used file information templates that are also Structured Data on Commons-driven (Information, Artwork, Art Photo, Book - for now). Users will be able to add their own.

![image](https://user-images.githubusercontent.com/9881645/166097934-0dcfefa5-33d4-4a4e-bfcf-eed9317bb1cf.png)

[Current wireframes](https://xd.adobe.com/view/fdf5a12c-9c30-4449-9eba-d1ea8523dddb-a8a6/screen/8155840d-c630-4bd8-802a-9acf02bb3624) by @lozanaross were based on a spreadsheet by Sandra, but need some tweaking and finalization (basically, there will be other custom statements that reflect current SDC modeling conventions). @trnstlntk will create these based on her knowledge of these modeling practices.

**Comment by lozanaross** [comment]
I think there is one additional TO DO with this issue.
- [ ] Check all this with commons community / relevant staff. 

I was thinking about this issue of how confusing it is to indicate what something depicts vs what it is a representation of - slightly controversial proposal, but do we have any chance of proposing 2 properties here to the community (instead of just the one): 1) representation of - to indicate what work of art the image is representing (there is already one such WD property although it's used differently of course: https://www.wikidata.org/wiki/Wikidata:Property_proposal/representation_of) 2) depicts - to indicate what the image is depicting - e.g. a sculpture on a pedestal, outdoors, etc.

**Comment by trnstlntk** [comment]
For reference, this is the code that @multichill uses to generate SDC and Wikitext (including the much-feared license templates) when uploading new files to Commons: https://github.com/multichill/toollabs/blob/master/bot/commons/wikidata_uploader.py#L398

**Comment by multichill** [comment]
> I think there is one additional TO DO with this issue.
> 
>     * [ ]  Check all this with commons community / relevant staff.
> 
> 
> I was thinking about this issue of how confusing it is to indicate what something depicts vs what it is a representation of - slightly controversial proposal, but do we have any chance of proposing 2 properties here to the community (instead of just the one): 1) representation of - to indicate what work of art the image is representing (there is already one such WD property although it's used differently of course: https://www.wikidata.org/wiki/Wikidata:Property_proposal/representation_of) 2) depicts - to indicate what the image is depicting - e.g. a sculpture on a pedestal, outdoors, etc.

The current consensus is documented at https://commons.wikimedia.org/wiki/Commons:Structured_data/Modeling/Depiction#Works_of_art and it doesn't include https://www.wikidata.org/wiki/Property:P4646 . P4646 is for performances.

**Comment by trnstlntk** [comment]
I am documenting this here: https://docs.google.com/document/d/1TTKmjg8pL4f2OZTrobeZcem_Ns-O8Y_cwHHWt9zFd2g/edit#
I'm still working on the help text but the structure should be in place.

The instructions reflect current SDC modeling best practices, and I feel pretty good and confident about these. However, the help text can still use a bit of improvement. More broadly, I think the documentation on Wikimedia Commons can still use a big improvement - community members don't spontaneously find Commons:Structured data/Modeling at all, and I think it would be very good to actually have dedicated documentation pages for the SDC equivalents of the basic information template, for visual artworks, and for books. I may put that on my to do list too.

**Comment by trnstlntk** [comment]
Following up on [#5043](https://github.com/OpenRefine/OpenRefine/issues/5043) (schema templates developed in the Wikibase extension), I am developing the current Commons-specific schema templates there. 

I am also in progress of developing documentation re: data modeling for artworks: https://commons.wikimedia.org/wiki/Commons:Structured_data/Modeling/Visual_artworks
