### ISSUE TITLE
Issue reporting in Wikibase edit schema, focused on the Wikimedia Commons use case

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/CommonsExtension#22]
When using OpenRefine's schema editor to prepare edits and uploads to Wikimedia Commons, users should get clear feedback (in the 'issues' tab) about what may go wrong in their edit/upload batches.

This feedback will in some cases be different from the generic feedback for any Wikibase (i.e. not just constraint related) and specific to Wikimedia Commons: think about feedback that concerns duplicate file names, file names with invalid characters...

- [ ] @trnstlntk to write specifications for this (what potential problems do we need to cover here; draft copy for clear error messages?..) - deadline May 31, 2022
- [ ] @wetneb to build this - deadline June 30, 2022

**Comment by trnstlntk** [comment]
I hope I got / remembered this one right from our team roadtripping exercise last week. Feel free to tweak.

**Comment by trnstlntk** [comment]
This one fell between the cracks somehow. Error reporting is important, and we talked about it quite a bit in various contexts.

I feel inclined to close this task (merely for cleanup purposes) because we are tackling this partly in different areas, example: https://github.com/OpenRefine/OpenRefine/issues/5032

**Comment by wetneb** [comment]
#5032 is about reporting errors after we attempted the upload
This GitHub issue seems to be about the "Issues" tab, which is about reporting problems before the upload (which is something we already have the infrastructure for). It is worth opening issues for issues related to file upload that should be flagged in this Issues tab, for instance like this one: https://github.com/OpenRefine/OpenRefine/issues/5181

**Comment by trnstlntk** [comment]
There's also this issue: https://github.com/OpenRefine/OpenRefine/issues/5192

I agree that separate issues are better as they emerge (I'm not sure if I'll ever be able to comprehensively list everything that may go wrong).
