### ISSUE TITLE
Review interface copy and tooltips in @Lozanaross wireframes dd Apr 26, 2022

### ISSUE THREAD

**Issue by lozanaross** [OpenRefine/CommonsExtension#23]
During an OpenRefine/SDC workshop at De Krook in Ghent, April 26, 2022, @lozanaross presented a new version of Wikimedia Commons wireframes: https://xd.adobe.com/view/fdf5a12c-9c30-4449-9eba-d1ea8523dddb-a8a6/

Several of these wireframes need a review by @trnstlntk

- [ ] General review of interface copy that is specific to Wikimedia Commons

- [ ] Create draft texts for tooltips - (i) icons which are newly introduced here

- [ ] For tooltips for structured data statements in the Schema dialog: investigate whether these are generically applicable to Commons or Wikidata (and hence be a Wikidata statement) or are really OR-specific (and hence need to be maintained outside Wikidata)

**Comment by lozanaross** [comment]
I'm making this an issue because it's useful to me too, ie. after the review is done, I'll probably need to update the wireframes again, so that we have a "single source of truth".

**Comment by lozanaross** [comment]
@trnstlntk It will be good if you can plan to do the interface copy review soon, so we can factor it in the user testing in June, thanks!

**Comment by trnstlntk** [comment]
> @trnstlntk It will be good if you can plan to do the interface copy review soon, so we can factor it in the user testing in June, thanks!

Guilt is burning in my chest, and I put it on top of my to do list for this week. Coming your way soon!

**Comment by lozanaross** [comment]
Brilliant - thanks Sandra! Didn't mean to guilt trip you, but coming back from my covid away time - i was like, right, what's next! I'll check out the comments on the wires before the end of the week. And I'm happy to look at the templates.

**Comment by trnstlntk** [comment]
Following up on [#5043](https://github.com/OpenRefine/OpenRefine/issues/5043) (schema templates developed in the Wikibase extension), I am developing the current Commons-specific schema templates there. We have decided to not use detailed tooltips for each individual statement, but rather to point to general documentation.
