### ISSUE TITLE
Build the UI to pick a template

### ISSUE THREAD

**Issue by lozanaross** [OpenRefine/CommonsExtension#24]
This relates specifically to the possibility to select templates from a dropdown, as well as possibility to save them (see latest  version of the wires below): 

![Image](https://user-images.githubusercontent.com/25489750/166148235-9335d8a8-72d6-475f-a97d-e6ab72f332bf.png)

**Comment by wetneb** [comment]
I would be in favour of building that in the Wikibase extension directly, since templates should be useful outside of Commons.

**Comment by lozanaross** [comment]
> I would be in favour of building that in the Wikibase extension directly, since templates should be useful outside of Commons.

@wetneb sounds good - should I move the issue to the general OpenRefine repo then (& add more context)?

**Comment by trnstlntk** [comment]
Closing this issue, because it is being worked on on the OpenRefine side: [#5043](https://github.com/OpenRefine/OpenRefine/issues/5043)
