### ISSUE TITLE
Build the UI to fill out an SDC template

### ISSUE THREAD

**Issue by lozanaross** [OpenRefine/CommonsExtension#26]
This relates to the schema tab UI that users get to fill out when they select a template, it goes beyond what is already supported in the generic WB extension UI. Pages 15-19 here: https://xd.adobe.com/view/d8b086f2-199a-4fcf-a1e8-8d939842b790-8de3/

**Comment by trnstlntk** [comment]
In progress as part of Wikibase extension, in [#5043](https://github.com/OpenRefine/OpenRefine/issues/5043)

**Comment by lozanaross** [comment]
I think this issue is outdated and the wires linked here are outdated. Perhaps we should close?

**Comment by trnstlntk** [comment]
Yes, closing because duplicate :-) Thanks!
