### ISSUE TITLE
User testing in June

### ISSUE THREAD

**Issue by lozanaross** [OpenRefine/CommonsExtension#28]
This issue serves as a deadline to complete and test a number of the minimum requirement issues to fulfil the original WMF grant with what we promised for a June deadline.

**Comment by wetneb** [comment]
We now have the 3.6-beta2 release, which can be used to test editing of SDC on existing files.
The 3.7-SNAPSHOT can be used to test the initial upload functionality.

**Comment by lozanaross** [comment]
FYI the mac version of the snapshot is giving me a 404: https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.openrefine&a=openrefine&v=3.7-SNAPSHOT&c=mac&p=dmg 

But i can try compiling from the master branch.

**Comment by trnstlntk** [comment]
I think we can close this issue, as this specific round of user testing is finished, and @lozanaross has followed up writing the relevant GitHub issues + we discussed prioritization. If you agree, feel free to close :D

**Comment by lozanaross** [comment]
I wanted to only link the report here after it was published, otherwise happy to close!
Here it is: https://commons.wikimedia.org/wiki/File:OpenRefineSummary_user_testing_June2022.pdf
