### ISSUE TITLE
Integrate thumbnail previews during the Wikimedia Commons batch file upload process

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/CommonsExtension#34]
See https://commons.wikimedia.org/wiki/Commons_talk:OpenRefine

Request received in a conversation in the Wikimedia Commons Telegram channel. During a batch upload process of media files, it is extremely helpful if one can (easily) see thumbnail previews of the media files that are being uploaded.

Some existing Wikimedia Commons (batch) upload tools support this indeed (the default [UploadWizard](https://commons.wikimedia.org/wiki/Special:UploadWizard), for instance), others don't ([Pattypan](https://commons.wikimedia.org/wiki/Commons:Pattypan) only shows previews of files and their infoboxes during the checking phase of the upload process, after all data has been prepared already).

OpenRefine is essentially a data-centric tool, so this may be a stretch, but it's good to have this request on the radar, as it makes a lot of sense IMO.

**Comment by lozanaross** [comment]
Wow, learning new things every day :-) Just transferred it. I hope that's ok!

**Comment by trnstlntk** [comment]
Separate issues for the three scenarios:

* Thumbnails for files already on Wikimedia Commons: https://github.com/OpenRefine/OpenRefine/issues/5295 (to be completed before end October 2022, as part of the Wikimedia SDC project)
* Thumbnails for files loaded from local machine: https://github.com/OpenRefine/OpenRefine/issues/5296 (to be done "later")
* Thumbnails for files from URL: https://github.com/OpenRefine/OpenRefine/issues/5297 (to be done "later")

As we now have these separate issues, I will close this one.
