### ISSUE TITLE
Selecting 'Start Over' button should clear previously set categories

### ISSUE THREAD

**Issue by j-sal** [OpenRefine/CommonsExtension#44]
In the parsing menu, when a user decides to 'Start Over', the category name(s) of the files to fetch should be empty, and previously set categories should be removed from the request sent to the backend, allowing for a new set of categories to be set.

**Comment by trnstlntk** [comment]
This is different from the default behavior in OpenRefine. For instance, starting over a project from Clipboard will show what the user entered previously. Let's stick with OpenRefine's default behavior, meaning that it's OK that the user sees the previously entered categories (and depth).
