### ISSUE TITLE
Allow people to remove Commons categories from the selected list, while listing desired categories to retrieve files from

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/CommonsExtension#52]
When I start the Commons extension, and I am listing the Commons categories I am interested in retrieving files from, I sometimes makes mistakes. I may have listed several categories (and their depth) but then may want to remove one or more of them again (because I changed my mind, I mistyped, etc)

E.g. in the example below:
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/9881645/188638378-1d478d2d-ecbe-4034-b1f8-4b3052983587.png">
_Oops! I absolutely do NOT want to load files from the Category:Sculptures in Amsterdam. Why would I? Sculptures in Rotterdam and Delft are way cooler._

It would be great to add the option to remove categories here, by adding a cross at the end of each line (behind the category depth field). If the user clicks that cross, the line will be deleted and files from the category will not be retrieved anymore.

We already use such a 'removing cross' in various other places in OpenRefine's interface, e.g. in the selection of (and removal of) reconciliation services:
<img width="313" alt="Screenshot 2022-09-06 at 14 42 03" src="https://user-images.githubusercontent.com/9881645/188638746-4daa51ac-5187-4441-8117-93a652bd059c.png">

**Comment by trnstlntk** [comment]
@lozanaross this is a really minimal addition - would you like to take a look at what this should look like, or is it simple enough to let @j-sal just have a go?

**Comment by j-sal** [comment]
@trnstlntk Do we want to remove the line with both the Category and its depth? or only the Category and keep the depth?
![image](https://user-images.githubusercontent.com/26920450/189891909-ff89f2ed-18c4-49f9-8930-ed6ea33d1c15.png)

**Comment by trnstlntk** [comment]
> @trnstlntk Do we want to remove the line with both the Category and its depth? or remove only the Category text and keep the depth?

Ooh, that looks nice already! Please remove everything on the line (and the line itself of course): both category and depth.

**Comment by lozanaross** [comment]
Great, the "x" works, I would suggest to just style it like it's looking right now for recon services - i.e. with the rectangular border, simply for consistency, but not a cruacial factor.
