### ISSUE TITLE
Filenames already reconciled when starting an OpenRefine project from Commons categories

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/CommonsExtension#56]
When users start an OpenRefine project using the Commons categories feature, it would be great if the file name column would already be reconciled against Wikimedia Commons.

Currently the project loads like this (checked M-id and categories options):
<img width="1449" alt="image" src="https://user-images.githubusercontent.com/9881645/192538862-cc6e286c-37d7-499b-9e6b-b734849b2dba.png">
Where the user still needs to manually reconcile the file names.

It would be great if a project would start with the file names already reconciled like this:
<img width="1449" alt="image" src="https://user-images.githubusercontent.com/9881645/192539146-aa811e19-8918-436d-88e9-c5f02d6d3d74.png">

**Comment by trnstlntk** [comment]
I think @antoine2711 was already thinking about a similar feature for the SPARQL importer extension as well?

**Comment by antoine2711** [comment]
> I think @antoine2711 was already thinking about a similar feature for the SPARQL importer extension as well?

Yes, we are currently working on that, and I will try to bring the code to do the same with the Commons Importer.

Regards, Antoine

**Comment by wetneb** [comment]
So, to work on this, I would recommend to follow what the "Use values as identifiers operation" is doing:
https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/operations/recon/ReconUseValuesAsIdentifiersOperation.java#L114-L137
(this shows how to create a reconciled cell, you should use similar code in your conversion from FileRecord to Row).

And then we should add reconciliation statistics and configuration on the column header (but that can be done in a second step). For this you could have a look at the Wikitext importer:
https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/importers/WikitextImporter.java#L751-L760
