### ISSUE TITLE
Extension name in project start UI should be *new* Wikimedia Commons (instead of Commons Extension)

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/CommonsExtension#62]
Currently the Commons Extension is called 'Commons Extension' in the blue project start 'Get data from' menu.

To be consistent with other data sources / extensions, let's rename it to `*new* Wikimedia Commons` per @lozanaross suggestions.

Wireframes:
![image](https://user-images.githubusercontent.com/9881645/194085450-b08b9460-7471-428e-aaec-50403571ab5d.png)

**Comment by wetneb** [comment]
Do we actually want the `*new* `? I understood it as an artifact from Lozana to help us identify the changes in the wireframes, but not go in the actual UI.

**Comment by lozanaross** [comment]
I think the new is nice - it's a new option for users after they install the extension. It attracts the attention of users, too, not just a wireframe artefact. But if you think it will "get old" too quickly, fine to skip it.

**Comment by wetneb** [comment]
Ok! My vote would be to do without (I indeed think it will not age well), or if we have it, then use some other way to emphasize the `new` (for instance with bold or italics, or have the `*` replaced by actual star icons). In my perception, using `*` in this way feels too informal (a bit like like adding `:-)` in some UI text).

**Comment by trnstlntk** [comment]
I agree with Antonin.

That said, it makes me think that it could be a nice pattern to have
"something that draws attention to a freshly installed extension". Making
the extension's name bold, e.g. until the user has actually clicked on it,
sounds like a nice simple first approach.

**Comment by j-sal** [comment]
Fixed by commit [9ecc29d](https://github.com/OpenRefine/CommonsExtension/commit/9ecc29ddab53c97aa292439c622f168177063ba8)
