### ISSUE TITLE
Rename 'Include nested category levels:' to 'Subcategory depth:'

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/CommonsExtension#67]
During user testing, @lozanaross asked users (without giving them instructions) to guess what the subcategory depth input field meant. Many people thought it was a checkbox and most couldn't guess what it was supposed to do (especially people unfamiliar with other tools to work with Wikimedia Commons categories).

<img width="777" alt="image" src="https://user-images.githubusercontent.com/9881645/195115031-01669c4d-5178-426b-9a23-ef92059cecec.png">

We suggest to rename the `Include nested category levels:` text in the interface to `Subcategory depth:` which is a bit shorter, and gives more indication that a number needs to be entered in the input field.

**Comment by j-sal** [comment]
Closed as per #66
