### ISSUE TITLE
Make usage of 'category depth' input field a bit clearer by greying out (until category is entered) and perhaps by integrating a counter 

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/CommonsExtension#68]
To make the function of the 'category depth' input box a bit clearer, @lozanaross suggests it should be greyed out until the user picks a category, then it becomes white.

Additionally, it could include a counter (currently users didn't understand they are supposed to type a number). If fetching only the current category means depth=0, perhaps the input box can be prefilled with a 0 by default, and when clicking the user gets a dropdown with more numbers to select?

**Comment by trnstlntk** [comment]
I think we can safely encourage/nudge users to go to a maximum depth of 6-ish categories - deeper will make the retrieval of files very slow I think? But what if a user wants to indeed enter a higher number (eg 11)?

**Comment by lozanaross** [comment]
If we implement a counter, maybe the counter only goes up to 6 (I like the idea of starting from 0, but that is still in a greyed out box until the category is picked, then the background becomes white and the user can increase the count up or down (with 6 as max value).

By counter I imagine something like this: https://i.stack.imgur.com/QAzfp.gif
(gif source is this page: https://stackoverflow.com/a/63332217 - don't know if script is actually good, just like the looks of the UI)

**Comment by wetneb** [comment]
I think the simplest and cleanest implementation of this would simply be to set the `<input>` field to have `type="number"`, which then uses the browser's native widget to let users input numbers.
