### ISSUE TITLE
Design a UI with which CommonsExtension users interact with Wikitext-specific GREL commands

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/CommonsExtension#7]
@j-sal is building various pieces of very helpful GREL syntax that will make it easier for users of OpenRefine's Commons Extension to parse and process Wikitext.

It would be good to have a dedicated UI with which users can choose and test these various GREL commands; ideally without even having to know/memorize them or look them up. It would also be good to have some preview functionality of what each operation will do.

For inspiration / input for this task:

- Sandra's wishlist of various things to parse from Wikitext: https://docs.google.com/document/d/1pFElwbRDBwXSZvuokd8OE1yWr2op1Zl2ckk0mg96OYQ/edit
- GREL commands that are either already implemented or in progress: https://github.com/OpenRefine/CommonsExtension/issues?q=is%3Aissue

**Comment by trnstlntk** [comment]
Work in progress!

Task to actually build this dialog: #21

**Comment by lozanaross** [comment]
Version 1 of this (i.e. what I think should be doable as a phase 1 to test with users, iterate, and potentially build up even fancier interactions later in the summer) is here: https://xd.adobe.com/view/fdf5a12c-9c30-4449-9eba-d1ea8523dddb-a8a6/  (pp.33-39) 

Feel free to add comments on the designs if anything is unclear.
