### ISSUE TITLE
‘Load at most’ does not work during step to configure parsing options

### ISSUE THREAD

**Issue by lozanaross** [OpenRefine/CommonsExtension#84]
This occurred during user testing in Sept / Oct session, if it's been fixed since then, we can close the issue. 

One user was loading categories with many files in them via the Commons extension and tried using the ‘Load at most [x] row(s) of data.’ User entered 7000, but got back over 9000 records and 12000 rows in the resulting project sheet.
 
Expected behaviour would be to get 7000 rows even if there are more files classified with the requested categories. 

Screenshots:
![Screenshot 2022-11-16 at 01 11 41](https://user-images.githubusercontent.com/25489750/202051886-d030b76e-3876-4084-9f8a-80ed7c01a04f.png)
![Screenshot 2022-11-16 at 01 13 36](https://user-images.githubusercontent.com/25489750/202051974-31c867a2-d5a5-4daa-9330-8c1fc2fa308d.png)
![Screenshot 2022-11-16 at 01 14 13](https://user-images.githubusercontent.com/25489750/202051977-4982bf64-f9d1-4bab-ac42-e5cb0221b97e.png)

**Comment by sunilnatraj** [comment]
@lozanaross Tested on latest version - the working is as expected
- Set the value for records to load 
- Click on Update preview 
- Data preview loads only the set number of records

@wetneb

**Comment by wetneb** [comment]
Thank you for trying to reproduce this! Beyond the data preview, did you also check if creating the project also respects this limit?

**Comment by sunilnatraj** [comment]
> Thank you for trying to reproduce this! Beyond the data preview, did you also check if creating the project also respects this limit?

@wetneb Yes the project gets created with the number of records as set in the preview

**Comment by wetneb** [comment]
Great, then let's close this indeed!
